<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <title>Single Page UI-Bootstrap</title>
        <meta name="description" content="Single page UI-bootstrap template with back-button support">
        <meta name="author" content="rhildred">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="stylesheet" href="css/main.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-route.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.13.4/ui-bootstrap.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.13.4/ui-bootstrap-tpls.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-scroll/0.7.2/angular-scroll.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular-touch.js"></script>
        <script src="js/singlepageui-bootstrap.js"></script>

        <!--[if lt IE 9]>
<script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
    </head>

    <body ng-app="app" ng-controller="navController">
        <div id="home" class="bookmark row">
            <div class="col-md-3">
                 <fieldset class="form-group">
                    <label for="quiztitle">Quiz Title:</label>
                    <input ng-model="quiz.title" type="text" class="form-control" id="quiztitle" placeholder="Enter quiz title">
                  </fieldset>
                <?php \RHildred\Editable\Markdown::render( __DIR__ . "/description.md"); ?>
            </div>
            <div class="col-md-9">
                <img id="filedrag" src="images/target-39708_960_720.png" alt="drop md file here" title="drop md file here" style="display:block;height:300px;margin:0 auto"/>
                <form ng-submit="submitFile()" style="width:60%;display:block;margin:10px auto" enctype="multipart/form-data" id="fileid">
                    <input type="file" name="fileToUpload" id="fileToUpload" style="display:inline">
                    <input class="btn btn-default" type="submit" value="Upload" name="submit">
                </form>
            </div>

        </div>
        <div class="navbar navbar-inverse {{navClass}}" role="navigation">
            <div class="navbar-header">

                <!-- note the ng-init and ng-click here: -->
                <button type="button" class="navbar-toggle" ng-init="navCollapsed = true" ng-click="navCollapsed = !navCollapsed">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">MdToQuiz</a>
            </div>

            <!-- note the ng-class here -->
            <div class="collapse navbar-collapse" ng-class="{'in':!navCollapsed}">

                <ul class="nav navbar-nav navbar-right">
                    <li du-scrollspy="about"><a href="#about" data-toggle="collapse" data-target=".navbar-collapse.in">About</a>
                    </li>
                    <li du-scrollspy="contact"><a href="#contact" data-toggle="collapse" data-target=".navbar-collapse.in">Contact</a>
                    </li>
                </ul>
            </div>
            <a href="#home" class="scrollToTop" ng-hide="bAboveMenu">TO TOP</a>
            <div ng-view></div>
        </div>
        <div class="bookmark row">
            <div class="col-md-7">
                <form ng-submit="uploadText">
                     <fieldset class="form-group">
                        <label for="markdowntext">Markdown:</label>
                        <textarea id="markdowntext" class="form-control" ng-model="quiz.markdown" placeholder="Enter Markdown Here"></textarea>
                    </fieldset>
                    <input type="submit" value="Send" class="btn btn-primary btn-md" />
                    <input type="reset" value="Reset" class="btn btn-primary btn-md" />
                </form>
            </div>
            <div class="col-md-5">
                <?php \RHildred\Editable\Markdown::render( __DIR__ . "/index.md"); ?>
            </div>
        </div>
        
        <div class="bookmark" id="about">
            <?php \RHildred\Editable\Markdown::render( __DIR__ . "/about.md"); ?>

        </div>
        <div class="bookmark" id="contact">
            <h2>Contact Rich Hildred</h2>
            <div style="overflow:hidden;height:350px;width:100%;">
                <script src="https://maps.google.com/maps/api/js"></script>
                <script>
                    google.maps.event.addDomListener(window, "load", function(){
                        var myOptions = {
                            zoom: 14,
                            center: new google.maps.LatLng(43.4531855, -80.55331509999996),
                            mapTypeId: google.maps.MapTypeId.ROADMAP,
                            scrollwheel: false
                        };
                        map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);
                        marker = new google.maps.Marker({
                            map: map,
                            position: new google.maps.LatLng(43.4531855, -80.55331509999996)
                        });
                        infowindow = new google.maps.InfoWindow({
                            content: "<b>Salesucation.com Inc.</b><br/>5-420 Erb St . W<br/>N2L6K6 Waterloo"
                        });
                        google.maps.event.addListener(marker, "click", function () {
                            infowindow.open(map, marker);
                        });
                        infowindow.open(map, marker);
                    });
                </script>
                <div id="gmap_canvas" style="height:350px;width:100%;"></div>
                <style>
                    #gmap_canvas img {
                        max-width: none!important;
                        background: none!important
                    }
                </style>
            </div>
            <h3>Inquiry</h3>
            <script type="text/javascript">
                var nLat = 43.4531855,nLong = -80.55331509999996;
                function init_map() {
                    var myOptions = {
                        scrollwheel: false,
                        zoom: 12,
                        center: new google.maps.LatLng(nLat, nLong),
                        mapTypeId: google.maps.MapTypeId.ROADMAP
                    };
                    map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);
                    marker = new google.maps.Marker({
                        map: map,
                        position: new google.maps.LatLng(nLat, nLong)
                    });
                    infowindow = new google.maps.InfoWindow({
                        content: "<b>Rich Hildred</b><br/>5-420 Erb St . W<br/>N2L6K6 Waterloo"
                    });
                    google.maps.event.addListener(marker, "click", function () {
                        infowindow.open(map, marker);
                    });
                    infowindow.open(map, marker);
                }
                google.maps.event.addDomListener(window, 'load', init_map);
            </script>
            <div class="col-md-4">

                <table>
                    <tbody>
                        <tr>
                            <td></td>
                            <td>5-420 Erb St. West</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>Suite 207</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>Waterloo, ON, N2L 6K6, Canada</td>
                        </tr>
                        <tr>
                            <td>Phone:</td>
                            <td>(855) 310-6344</td>
                        </tr>
                        <tr>
                            <td>Phone:</td>
                            <td>(519) 594-0900</td>
                        </tr>
                        <tr>
                            <td>Fax:</td>
                            <td>(519) 957-2471</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-md-8">
                <form ng-submit="submitBugReport()">
                     <fieldset class="form-group">
                        <label for="contactemail">Email:</label>
                        <input id="contactemail" class="form-control" type="email" ng-model="contact.email" placeholder="Reply email address" />
                    </fieldset>
                     <fieldset class="form-group">
                        <label for="contactsubject">Subject:</label>
                        <input id="contactsubject" class="form-control" type="text" ng-model="contact.subject" placeholder="Subject of your inquiry" />
                    </fieldset>
                     <fieldset class="form-group">
                        <label for="contactmessage">Message:</label>
                        <textarea id="contactmessage" class="form-control" ng-model="contact.message" placeholder="Your Inquiry"></textarea>
                    </fieldset>
                    <input type="submit" value="Send" class="btn btn-primary btn-md" />
                    <input type="reset" value="Reset" class="btn btn-primary btn-md" />
                    <span class="alert alert-success" ng-hide="!successmessage">{{successmessage}}</span><span class="alert alert-warning" ng-hide="!errormessage">{{errormessage}}</span>
                    <br />
                </form>
            </div>
        </div>

        <hr/>&copy; Rich Hildred <script> document.write( new Date().getFullYear())</script>


    </body>
</html>
